### ISSUE TITLE
'Viewpoint Detector' Question

### ISSUE THREAD

**Issue by dothuhahb98** [weizhou-geek/VGCN-PyTorch#1]
Hi,
In the dataset which is 'cviqd_resize_imgtrain' and 'cviqd_resize_imgtest' folder, containing 20 viewport images.
It is described in Viewpoint Detector (in the paper). I want to dive into this work, and it seems like lack of this work in your project.  Can you provide more about it?

**Comment by Xudoudou1996** [comment]
> Hi,
> In the dataset which is 'cviqd_resize_imgtrain' and 'cviqd_resize_imgtest' folder, containing 20 viewport images.
> It is described in Viewpoint Detector (in the paper). I want to dive into this work, and it seems like lack of this work in your project. Can you provide more about it?

The code for 'Viewpoint Detector' is on another server. We will organize the code and release it soon.

**Comment by dothuhahb98** [comment]
thank you
