### ISSUE TITLE
"Affinity Matrix" Question 

### ISSUE THREAD

**Issue by dothuhahb98** [weizhou-geek/VGCN-PyTorch#2]
Thank you for you distribution. 

I am trying to test your model in my dataset. 
In your paper, you mentioned about how to calculate the Affinity matrix which was represented in matrix (20x20). I am trying to calculate by using Matlab, but I have some misunderstanding about the input of it.
Can you clarifies it and give some tutorial about the how you create the Affinity matrix.

Thanks a lot.

**Comment by weizhou-geek** [comment]
When we get the selected viewports, if the distance between center point of viewport A and viewport B is larger than 45°, then the edge is between the two nodes is 0, otherwise, the edge is set as 1. We can obtain the location of center point in fov_selection folder.

**Comment by dothuhahb98** [comment]
I got it.
Thanks a lot.
